language: ruby
rvm: 2.5.5
sudo: false

before_install:
 - gem install hiptest-publisher
#  - "hiptest-publisher -c cucumber.conf --token=$SECRET_TOKEN --only=features,step_definitions --test-run-id=3507"
 - "hiptest-publisher -c cucumber.conf --only=features,step_definitions --test-run-id=388151"

script:
 - bundle exec cucumber --format json --out results.json

after_script:
  # - hiptest-publisher -c cucumber.conf --token=$SECRET_TOKEN --push=results.json --test-run-id=3507
  - hiptest-publisher -c cucumber.conf --push=results.json --test-run-id=388151
